# Generated by Django 4.2 on 2024-03-03 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestModels', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='City',
            new_name='District',
        ),
    ]
