# Generated by Django 4.2 on 2024-03-07 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TestModels', '0003_mandal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mandal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestModels.mandal')),
            ],
        ),
    ]
